# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.3'

gem 'puma', '~> 6.0'
gem 'rails', '~> 7.1'

gem 'aws-sdk-dynamodb', '~> 1.0'
gem 'aws-sdk-ec2', '~> 1.0'
gem 'aws-sdk-secretsmanager', '~> 1.0'

gem 'rack-cors', '~> 2.0'
gem 'solid_queue', '~> 1.0'

# SQLite for Solid Queue job storage
gem 'sqlite3', '~> 1.7'

gem 'bootsnap', require: false

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]

gem 'jwt', '~> 2.7'
gem 'lograge', '~> 0.14'

# ActionCable adapter for production-ish real-time updates
# For local/embedded use we can use the async adapter; Redis is recommended in prod.
gem 'redis', '~> 5.0'

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
  gem 'rspec-rails', '~> 6.1'
  gem 'rubocop', '~> 1.60', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  gem 'simplecov', require: false
  gem 'webmock', '~> 3.0'
end
