title: SEEO
name: SEEO
description: "A full-stack AWS orchestration tool for secure, TTL-bound ephemeral environments."
show_downloads: false
baseurl: /seeo-aws-orchestrator
url: https://samueladegnan.github.io
