title: SEEO | Multi-cloud Control-plane Prototype
name: SEEO | Multi-cloud Control-plane Prototype
description: "SEEO, a multi-cloud control-plane prototype for short-lived environments across AWS, Azure, Google Cloud, and OCI."
lang: en
author: Samuel Degnan
repository: samueladegnan/seeo-aws-orchestrator
show_downloads: false
baseurl: /seeo-aws-orchestrator
url: https://samueladegnan.github.io
